AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template to deploy a Lambda function with API Gateway

Resources:
  ApplicationsInsightsSLO:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      Handler: bootstrap
      FunctionName: ApplicationsInsightsSLO
      PackageType: Zip
      Runtime: provided.al2
      Architectures: 
       - arm64
      CodeUri: . # Path to the directory containing the function code
      Description: A simple "Hello, World!" Lambda function
      MemorySize: 128
      Timeout: 5
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        AppSLOEvent:
          Type: Api
          Properties:
            Path: /hello
            Method: get

