AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Quarkus HTTP - com.amazon.quarkus.demo::pet-store
Globals:
  Api:
    EndpointConfiguration: REGIONAL
    BinaryMediaTypes:
      - "*/*"

Resources:
  AWSLambdaCustomRuntimeJava:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.sab.LambdaHandler::handleRequest
      Runtime: provided
      CodeUri: function.zip
      MemorySize: 128
      Policies: AWSLambdaBasicExecutionRole
      Tracing: Active
      Timeout: 15
      Environment:
        Variables:
          DISABLE_SIGNAL_HANDLERS: true